# Generated by Django 2.1.2 on 2019-01-29 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiluseriinfo',
            old_name='site_portfolio',
            new_name='adrese_webi',
        ),
    ]
