# Generated by Django 2.1.2 on 2019-01-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190124_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portofolio_site',
            new_name='portfolio_site',
        ),
    ]
